import { Category } from '../enums';

export const CATEGORY_KEYWORDS: Record<Category, string[]> = {
  [Category.LOVE]: [
    // Español
    'amor',
    'pareja',
    'relacion',
    'enamorado',
    'enamorada',
    'novio',
    'novia',
    'romance',
    'beso',
    'querer',
    'amar',
    'corazon',
    'sentimiento',
    // English
    'love',
    'relationship',
    'boyfriend',
    'girlfriend',
    'romance',
    'kiss',
  ],

  [Category.CAREER]: [
    // Español
    'trabajo',
    'empleo',
    'carrera',
    'jefe',
    'oficina',
    'sueldo',
    'profesion',
    'proyecto',
    'empresa',
    'negocio',
    'ascenso',
    'despido',
    // English
    'work',
    'job',
    'career',
    'boss',
    'office',
    'salary',
    'business',
  ],

  [Category.HEALTH]: [
    // Español
    'salud',
    'enfermedad',
    'medico',
    'doctor',
    'hospital',
    'medicina',
    'dolor',
    'enfermo',
    'cura',
    'tratamiento',
    'sintoma',
    // English
    'health',
    'illness',
    'doctor',
    'hospital',
    'medicine',
    'pain',
    'sick',
  ],

  [Category.FAMILY]: [
    // Español
    'familia',
    'padre',
    'madre',
    'hijo',
    'hija',
    'hermano',
    'hermana',
    'abuelo',
    'abuela',
    'tio',
    'tia',
    'primo',
    'pariente',
    // English
    'family',
    'father',
    'mother',
    'son',
    'daughter',
    'brother',
    'sister',
  ],

  [Category.DEATH]: [
    // Español
    'muerte',
    'muerto',
    'fallecimiento',
    'perdida',
    'morir',
    'difunto',
    'cementerio',
    'funeral',
    'luto',
    'tristeza',
    // English
    'death',
    'dead',
    'loss',
    'passed away',
    'die',
    'funeral',
  ],

  [Category.FUTURE]: [
    // Español
    'futuro',
    'destino',
    'mañana',
    'proximo',
    'venir',
    'pronto',
    'prediccion',
    'espera',
    'llegara',
    // English
    'future',
    'destiny',
    'tomorrow',
    'next',
    'coming',
    'soon',
    'prediction',
  ],

  [Category.MONEY]: [
    // Español
    'dinero',
    'plata',
    'finanzas',
    'financiero',
    'financiera',
    'inversion',
    'deuda',
    'rico',
    'pobre',
    'ahorros',
    'prestamo',
    'billete',
    'banco',
    'economico',
    'economia',
    'exito',
    'exitoso',
    // English
    'money',
    'finance',
    'financial',
    'investment',
    'debt',
    'rich',
    'poor',
    'savings',
    'success',
  ],

  [Category.SPIRITUALITY]: [
    // Español
    'espiritu',
    'alma',
    'karma',
    'energia',
    'tarot',
    'astral',
    'chakra',
    'meditacion',
    'espiritual',
    'oracion',
    'angel',
    // English
    'spirit',
    'soul',
    'karma',
    'energy',
    'tarot',
    'astral',
    'meditation',
  ],

  // GENERAL no tiene keywords (es el fallback por defecto)
  [Category.GENERAL]: [],
};
