# Project identification
sonar.projectKey=OiujaAPI
sonar.projectName=Ouija Virtual Backend

# SonarQube server configuration
sonar.host.url=http://127.0.0.1:9000
sonar.token=${env.SONAR_TOKEN}

# Source code location
sonar.sources=src
sonar.tests=test

# Exclusions (código de producción)
sonar.exclusions=\
  **/node_modules/**,\
  **/dist/**,\
  **/coverage/**,\
  **/*.spec.ts,\
  **/*.e2e-spec.ts,\
  **/prisma/migrations/**,\
  **/scripts/**

# Test exclusions (archivos NO-test dentro de carpetas de test)
sonar.test.inclusions=**/*.spec.ts,**/*.e2e-spec.ts

# Coverage
sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Encoding
sonar.sourceEncoding=UTF-8
